[[redirects]]
    from='/api/darksky/*'
    to='https://api.darksky.net/forecast/0a9c9e4db3dc47f565165acc0aa9c9fe/:splat' 
    status= 200
    force=true

[[redirects]]
    from='/api/openstreetmap/*' 
    to='https://nominatim.openstreetmap.org/reverse?format=json&lat=:lat&lon=:lon&zoom=10&addressdetails=1' 
    status=200
    force=true
    query={lon=':lon', lat=':lat'}

[[redirects]]
    from='/api/geolocation'
    to='http://ip-api.com/json/'
    status=200
    force=true